<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="0" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="7020" started-at="2018-09-10T00:41:42Z" finished-at="2018-09-10T00:41:49Z">
    <groups>
    </groups>
    <test name="HomePageUploadFileTestTest" duration-ms="3249" started-at="2018-09-10T00:41:42Z" finished-at="2018-09-10T00:41:45Z">
      <class name="com.dropbox.test.HomePageUploadFileTest">
        <test-method status="FAIL" signature="dropboxLogin()[pri:0, instance:com.dropbox.test.HomePageUploadFileTest@654f0d9c]" name="dropboxLogin" is-config="true" duration-ms="3212" started-at="2018-09-10T00:41:42Z" finished-at="2018-09-10T00:41:45Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.HomePageUploadFileTest.dropboxLogin(HomePageUploadFileTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropboxLogin -->
        <test-method status="SKIP" signature="dropboxHome()[pri:0, instance:com.dropbox.test.HomePageUploadFileTest@654f0d9c]" name="dropboxHome" duration-ms="0" started-at="2018-09-10T00:41:45Z" finished-at="2018-09-10T00:41:45Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.HomePageUploadFileTest.dropboxLogin(HomePageUploadFileTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropboxHome -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.dropbox.test.HomePageUploadFileTest@654f0d9c]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-09-10T00:41:45Z" finished-at="2018-09-10T00:41:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dropbox.test.HomePageUploadFileTest -->
    </test> <!-- HomePageUploadFileTestTest -->
    <test name="LoginLogoutTest" duration-ms="797" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:46Z">
      <class name="com.dropbox.test.LoginLogoutTest">
        <test-method status="FAIL" signature="dropboxLogin()[pri:0, instance:com.dropbox.test.LoginLogoutTest@481a996b]" name="dropboxLogin" is-config="true" duration-ms="772" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:46Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.LoginLogoutTest.dropboxLogin(LoginLogoutTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropboxLogin -->
        <test-method status="SKIP" signature="userLogout()[pri:0, instance:com.dropbox.test.LoginLogoutTest@481a996b]" name="userLogout" duration-ms="0" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:46Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.LoginLogoutTest.dropboxLogin(LoginLogoutTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userLogout -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.dropbox.test.LoginLogoutTest@481a996b]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dropbox.test.LoginLogoutTest -->
    </test> <!-- LoginLogoutTest -->
    <test name="CreateNewFolderTest" duration-ms="2782" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:49Z">
      <class name="com.dropbox.test.HomePageUploadFileTest">
        <test-method status="PASS" signature="BrowserNavigation()[pri:0, instance:com.dropbox.test.HomePageUploadFileTest@654f0d9c]" name="BrowserNavigation" is-config="true" duration-ms="4263" started-at="2018-09-10T00:41:29Z" finished-at="2018-09-10T00:41:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserNavigation -->
        <test-method status="PASS" signature="BrowserNavigation()[pri:0, instance:com.dropbox.test.LoginLogoutTest@481a996b]" name="BrowserNavigation" is-config="true" duration-ms="4745" started-at="2018-09-10T00:41:33Z" finished-at="2018-09-10T00:41:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserNavigation -->
        <test-method status="PASS" signature="BrowserNavigation()[pri:0, instance:com.dropbox.test.CreateNewFolderTest@35ef1869]" name="BrowserNavigation" is-config="true" duration-ms="4384" started-at="2018-09-10T00:41:38Z" finished-at="2018-09-10T00:41:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrowserNavigation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dropbox.test.HomePageUploadFileTest@654f0d9c]" name="tearDown" is-config="true" duration-ms="2334" started-at="2018-09-10T00:41:49Z" finished-at="2018-09-10T00:41:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dropbox.test.LoginLogoutTest@481a996b]" name="tearDown" is-config="true" duration-ms="2310" started-at="2018-09-10T00:41:52Z" finished-at="2018-09-10T00:41:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.dropbox.test.CreateNewFolderTest@35ef1869]" name="tearDown" is-config="true" duration-ms="2318" started-at="2018-09-10T00:41:54Z" finished-at="2018-09-10T00:41:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dropbox.test.HomePageUploadFileTest -->
      <class name="com.dropbox.test.CreateNewFolderTest">
        <test-method status="FAIL" signature="dropboxLogin()[pri:0, instance:com.dropbox.test.CreateNewFolderTest@35ef1869]" name="dropboxLogin" is-config="true" duration-ms="2775" started-at="2018-09-10T00:41:46Z" finished-at="2018-09-10T00:41:49Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.CreateNewFolderTest.dropboxLogin(CreateNewFolderTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dropboxLogin -->
        <test-method status="SKIP" signature="createNewFolder()[pri:0, instance:com.dropbox.test.CreateNewFolderTest@35ef1869]" name="createNewFolder" duration-ms="0" started-at="2018-09-10T00:41:49Z" finished-at="2018-09-10T00:41:49Z">
          <exception class="com.dropbox.core.BadRequestException">
            <message>
              <![CDATA[Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.dropbox.core.BadRequestException: Error in call to API function "users/get_current_account": Invalid authorization value in HTTP header "Authorization": "Bearer".  Expecting "Bearer <oauth2-access-token>".
at com.dropbox.core.DbxRequestUtil.unexpectedStatus(DbxRequestUtil.java:298)
at com.dropbox.core.v2.DbxRawClientV2$1.execute(DbxRawClientV2.java:115)
at com.dropbox.core.v2.DbxRawClientV2.executeRetriable(DbxRawClientV2.java:284)
at com.dropbox.core.v2.DbxRawClientV2.rpcStyle(DbxRawClientV2.java:102)
at com.dropbox.core.v2.users.DbxUserUsersRequests.getCurrentAccount(DbxUserUsersRequests.java:120)
at com.dropbox.base.DropboxAPI.dropBoxAuth(DropboxAPI.java:40)
at com.dropbox.pageObjects.SignupLoginPage.userLoggedIn(SignupLoginPage.java:105)
at com.dropbox.test.CreateNewFolderTest.dropboxLogin(CreateNewFolderTest.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.dropbox.core.BadRequestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewFolder -->
        <test-method status="SKIP" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.dropbox.test.CreateNewFolderTest@35ef1869]" name="tearDown" is-config="true" duration-ms="0" started-at="2018-09-10T00:41:49Z" finished-at="2018-09-10T00:41:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.dropbox.test.CreateNewFolderTest -->
    </test> <!-- CreateNewFolderTest -->
  </suite> <!-- Suite -->
</testng-results>
